#cloud-config

preserve_hostname: true

hostname: "{{ vm_hostname }}"  # Optional: remove this if set by the script

users:
  - name: devops
    shell: /bin/bash
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    plain_text_passwd: "supersecurepassword"  # ⚠️ Use only in safe, non-prod environments
    ssh_authorized_keys:
      - ssh-rsa AAAAB3...your_pub_key_here

keyboard:
  layout: se

locale: en_US.UTF-8
timezone: Europe/Stockholm

packages:
  - python3
  - python3-pip
  - git
  - curl
  - docker.io
  - ansible
  - net-tools
  - iproute2

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - pip3 install --upgrade pip
  - pip3 install jinja2 netaddr pyyaml
  - git clone https://github.com/kubernetes-sigs/kubespray.git /opt/kubespray
  - cd /opt/kubespray
  - pip3 install -r requirements.txt
  - cp -rfp inventory/sample inventory/mycluster
  - |
    IPS=(192.168.1.101 192.168.1.102 192.168.1.103)  # <--- set your node IPs
    CONFIG_FILE=inventory/mycluster/hosts.yaml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
  - ansible-playbook -i inventory/mycluster/hosts.yaml cluster.yml -b -v